services:
  app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: docker-compose_test
    command: go run cmd/main.go

  db:
    image: postgres:18.0-alpine3.22
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=123456
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:80

volumes:
  pgdata:
